name: 🔐 SecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # ─── Job 1 : SAST avec Semgrep ───────────────────────────────
  semgrep:
    name: 🔍 SAST - Semgrep
    runs-on: ubuntu-latest
    steps:
      # SHA complet = immuable = protection supply chain
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run Semgrep
        uses: semgrep/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d # v1
        with:
          config: >-
            p/python
            p/secrets
            p/owasp-top-ten

  # ─── Job 2 : Secrets avec GitLeaks ──────────────────────────
  gitleaks:
    name: 🔑 Secrets - GitLeaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b2981b2743e9e96e25e18b # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ─── Job 3 : Tests unitaires ─────────────────────────────────
  tests:
    name: 🧪 Tests unitaires
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pytest
      - name: Run tests
        run: pytest tests/ -v
